name: build with conda

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.7, 3.8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - run: conda install openmpi rdkit pytorch torchvision cpuonly -c pytorch

    - name: install torch-geometric dependencies
      run: pip install --verbose --no-cache-dir torch-scatter torch-sparse torch-cluster torch-geometric

    - name: Install the package
      run: pip install .[test] -v
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pytest --cov=swan tests
